version: "3"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
        expose:
            - 9200
        ports: 
            - "9200:9200"
            - "9300:9300"
        volumes:
            - esdata:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node

    kibana:
        image: docker.elastic.co/kibana/kibana:6.0.0
        links:
            - "elasticsearch"
        ports:
            - "5601:5601"
        depends_on: 
            - elasticsearch

    fluentd:
        build: ./fluentd
        volumes:
            - ./fluentd:/fluentd/etc
        links:
            - "elasticsearch"
        ports:
            - "24224:24224"
            - "24224:24224/udp"

volumes:
    esdata:
        driver: local