version: "3"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
        ports: 
            - "9200:9200"
            - "9300:9300"
        volumes:
            - esdata1:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node

volumes:
    esdata1:
        driver: local