version: "3"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
        ports: 
            - "9200:9200"
            - "9300:9300"
        volumes:
            - esdata1:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node
    kibana:
        image: docker.elastic.co/kibana/kibana:6.0.0
        links:
            - "elasticsearch"
        ports:
            - "5601:5601"
        depends_on: 
            - elasticsearch

volumes:
    esdata1:
        driver: local